on:
  workflow_dispatch:
    inputs:
      buildVersion: 
        description: 'Which version'
        required: true
        default: '1.1.X'
      appToDeploy: 
        description: 'Which application'
        required: true
        default: 'foo|bar'

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    env:
      WHAT: ${{ github.event.inputs.appToDeploy }}
      IS_FOO: ${{ github.event.inputs.appToDeploy == 'foo' }}

    steps:
      - name: set version
        run: | 
          VER=1.3.2
          echo "VERSION=$VER" >> $GITHUB_ENV
          
      - name: determine minor version
        run: |
          VER=`echo ${{ env.VERSION }} | cut -d "." -f 2`
          echo "MINOR_VERSION=$VER" >> $GITHUB_ENV
          
      - name: Deploy application
        if: ${{ env.MINOR_VERSION == 0 }}
        run:
          echo 'ZERO'

      - name: Deploy application
        if: ${{ env.MINOR_VERSION == 1 }}
        run:
          echo 'ONE'

      - name: Deploy application
        if: ${{ env.MINOR_VERSION > 1 && env.IS_FOO }}
        run:
          echo 'GREATER - foo'        
