name: detached-workflow-dispatch
on:
  push:
    branches:
      feature/changereadme
  workflow_dispatch:
    inputs:
      name:
        description: What is in a name?
        required: true
        default: 'world'
jobs:
  myJob:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo 'Hello ${{ github.event.inputs.name }}'
