name: learn-github-actions
on: [push]
jobs: 
   check-bats-version:
      runs-on: ubuntu-latest
      steps:
         - name: checkout code with submodules 
           uses: actions/checkout@v2
           with:
              submodules: true
         - name: setup node 10.13
           uses: actions/setup-node@v1
           with:
             node-version: 10.13
         - run: npm install -g bats
         - run: bats -v
         - name: 'string fun'
           if: ${{ true && false }}
           run: echo '${{ format('-{0}-', env.REF_TAG) }}'
           env:
             REF_TAG: ${{ github.ref == 'develop' && 'dev' || '' }} 
