name: learn-github-actions
on: [pull_request]
jobs: 
   check-bats-version:
      runs-on: ubuntu-latest
      steps:
         - name: checkout code with submodules 
           uses: actions/checkout@v2
           with:
              submodules: true
         - name: setup node 10.13
           uses: actions/setup-node@v1
           with:
             node-version: 10.13
         - run: npm install -g bats
         - run: bats -v
         - run: echo "Hello World" >> myfile.txt
         - run: git add .
         - run: git commit -m "adding myfile on push"
         - run: git push
         
