# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        env: 
          DEV: ${{secrets.HELLO_WORLD_JSON}}
        run: |
          echo "$DEV" >> foo/hello_world.json
          cp foo/hello_world.json foo/hello_world2.json
          zip -r foo.zip foo

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        uses: actions/upload-artifact@v2
        with: 
          name: example
          path: foo.zip
          if-no-files-found: error
