# This is a basic workflow to help you get started with Actions

name: example-manual

# Controls when the action will run. 
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
        name:
           description: 'Enter name'
           required: true
           default: 'foo'
        address:
           description: 'Enter address'
           required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  noop:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - run: echo 'noop'
      
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    env: 
       NAME: ${{ github.event.inputs.name }}
       IS_FOO: ${{ NAME == 'foo' }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ github.event.inputs.address || 'default' }}

      - uses: actions/github-script@v3
        id: set-result
        with:
          script: return ${{ fromJSON(github.run_number) }} + 200 
          result-encoding: string

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo ${{ steps.set-result.outputs.result }}
          
      - name: Run another
        if: IS_FOO
        run: echo Hiya foo
     
      - run: docker ps -a
